#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname "$0")/_keepassxc_cli_with_options"

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7" notes="$8"

while IFS= read -r -d '/' group; do
	path+="${group}/"
	"${_keepassxc_cli_with_options}" "${options}" mkdir "${keychain}" "${path::-1}" <<< "${keychain_password}" &>/dev/null || true
done <<< "${name}"

"${_keepassxc_cli_with_options}" "${options}" add --password-prompt "${keychain}" ${account:+--username "${account}"} ${url:+--url "${url}"} ${notes:+--notes "${notes}"} "${name}" << EOF
${keychain_password}
${password}
EOF
