#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname -- "${BASH_SOURCE[0]}")/_keepassxc_cli_with_options"

IFS= read -r keychain_password
IFS= read -r password

options="$1" keychain="$2" name="$3" account="$4" url="$5" notes="$6"

while IFS= read -r -d '/' group; do
	path+="${group}/"
	"${_keepassxc_cli_with_options}" "${options}" mkdir "${keychain}" "${path::-1}" <<< "${keychain_password}" &>/dev/null || true
done <<< "${name}"

"${_keepassxc_cli_with_options}" "${options}" add --password-prompt "${keychain}" ${account:+--username "${account}"} ${url:+--url "${url}"} ${notes:+--notes "${notes}"} "${name}" <<EOF
${keychain_password}
${password}
EOF
