#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname -- "${BASH_SOURCE[0]}")/_keepassxc_cli_with_options"

IFS= read -r keychain_password
IFS= read -r password

# options="$1" keychain="$2" name="$3" account="$4" url="$5"
options="$1" keychain="$2" name="$3"

"${_keepassxc_cli_with_options}" "${options}" edit --password-prompt "${keychain}" "${name}" <<EOF
${keychain_password}
${password}
EOF
