#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname -- "${BASH_SOURCE[0]}")/_keepassxc_cli_with_options"

IFS= read -r keychain_password

options="$1" keychain="$2"

echo "\"${_keepassxc_cli_with_options}\" \"${options}\" show \"${keychain}\" {4} <<< \"${keychain_password}\""
