#!/usr/bin/env bash
set -euo pipefail
parse_options="$(dirname "$0")/../parse_options"
"$(dirname "$0")/_require"

options="$1" keychain="$2"

declare -a cmd_options=()
while IFS=$'\t' read -r key value; do
	case "${key}" in
		keyfile) cmd_options+=("--set-key-file" "${value}") ;;
	esac
done < <("${parse_options}" "${options}")

if [[ -p /dev/stdin ]]; then
	IFS= read -r password
	keepassxc-cli db-create --quiet "${cmd_options[@]}" --set-password "${keychain}" << EOF
${password}
${password}
EOF
else
	keepassxc-cli db-create "${cmd_options[@]}" --set-password "${keychain}"
fi
