#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname -- "${BASH_SOURCE[0]}")/_keepassxc_cli_with_options"

IFS= read -r keychain_password

# options="$1" keychain="$2" rename="$3" name="$4" account="$5" url="$6"
options="$1" keychain="$2" rename="$3" name="$4"

title="${rename##*/}"

if [[ "$(dirname -- "${rename}")" == "$(dirname -- "${name}")" ]]; then
	# same group, rename only
	"${_keepassxc_cli_with_options}" "${options}" edit --title "${title}" "${keychain}" "${name}" <<< "${keychain_password}"
else
	# different group, move and rename
	path=""
	while IFS= read -r -d '/' group; do
		path+="${group}/"
		"${_keepassxc_cli_with_options}" "${options}" mkdir "${keychain}" "${path::-1}" <<< "${keychain_password}" &>/dev/null || true
	done <<< "${rename}"

	"${_keepassxc_cli_with_options}" "${options}" mv "${keychain}" "${name}" "${path}" <<< "${keychain_password}"
	"${_keepassxc_cli_with_options}" "${options}" edit --title "${title}" "${keychain}" "${path}${name##*/}" <<< "${keychain_password}"
fi
