#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname "$0")/_keepassxc_cli_with_options"

options="$1" keychain="$2"

"${_keepassxc_cli_with_options}" "${options}" open "${keychain}"
