FROM ubuntu:latest AS base
WORKDIR /root/.local/share/pw
COPY DEPENDENCIES .
RUN apt-get update && apt-get install -y \
    $(cat DEPENDENCIES) \
    file \
    parallel \
    xclip \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

FROM base AS pw
WORKDIR /root/.local/share/pw
COPY src src
COPY examples examples
COPY lib lib
COPY plugins plugins
COPY version.txt .
RUN ln -s /opt/pw/src/pw /usr/local/bin/pw
WORKDIR /workspaces
COPY container/entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]

FROM pw AS test
WORKDIR /root/.local/share/pw
COPY test test
RUN test/bats/bin/bats test
