#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7" notes="$8"

_iterate_dirs() {
  local IFS=/ path=""
  for dir in ${name}; do
    path+="${dir}/"
    echo "${path}"
  done
}

mapfile -t dirs < <(_iterate_dirs)
for (( i = 0; i < ${#dirs[@]} - 1; i++ )); do
  "${_keepassxc_cli_with_args}" "${options}" mkdir "${keychain}" "${dirs[i]::-1}" <<< "${keychain_password}" &>/dev/null || true
done

"${_keepassxc_cli_with_args}" "${options}" add --password-prompt "${keychain}" ${account:+--username "${account}"} ${url:+--url "${url}"} ${notes:+--notes "${notes}"} "${name}" << EOF
${keychain_password}
${password}
EOF
