#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain="$2" password="$3" name="$4" account="$5" url="$6" notes="$7"

_iterate_dirs() {
  local IFS=/ path=""
  for dir in ${name}; do
    path+="${dir}/"
    echo "${path}"
  done
}

mapfile -t dirs < <(_iterate_dirs)
for (( i = 0; i < ${#dirs[@]} - 1; i++ )); do
  "${_keepassxc_cli_with_args}" "${options}" mkdir "${keychain}" "${dirs[i]::-1}" <<< "${PW_KEYCHAIN_PASSWORD}" &>/dev/null || true
done

"${_keepassxc_cli_with_args}" "${options}" add --password-prompt "${keychain}" ${account:+--username "${account}"} ${url:+--url "${url}"} ${notes:+--notes "${notes}"} "${name}" << EOF
${PW_KEYCHAIN_PASSWORD}
${password}
EOF
