#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

keychain="$1" password="$2" name="$3" account="$4" url="$5" notes="$6"

_iterate_dirs() {
  local IFS=/ path=""
  for dir in ${name}; do
    path+="${dir}/"
    echo "${path}"
  done
}

mapfile -t dirs < <(_iterate_dirs)
for (( i = 0; i < ${#dirs[@]} - 1; i++ )); do
  "${_keepassxc_cli_with_args}" mkdir "${keychain}" "${dirs[i]::-1}" <<< "${PW_KEYCHAIN_PASSWORD}" &>/dev/null || true
done

"${_keepassxc_cli_with_args}" add --password-prompt "${keychain}" ${account:+--username "${account}"} ${url:+--url "${url}"} ${notes:+--notes "${notes}"} "${name}" << EOF
${PW_KEYCHAIN_PASSWORD}
${password}
EOF
