#!/usr/bin/env bash
set -euo pipefail

options="$1" command="$2" keychain="$3"

if [[ -p /dev/stdin ]]
then IFS= read -r keychain_password
else IFS= read -rsp "Enter password to unlock ${keychain}:"$'\n' keychain_password
fi

echo "${keychain_password}"
