#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain="$2" password="$3" name="$4" account="$5" url="$6"

"${_keepassxc_cli_with_args}" "${options}" edit --password-prompt "${keychain}" "${name}" << EOF
${PW_KEYCHAIN_PASSWORD}
${password}
EOF
