#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname "$0")/_keepassxc_cli_with_options"

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7"

"${_keepassxc_cli_with_options}" "${options}" edit --password-prompt "${keychain}" "${name}" << EOF
${keychain_password}
${password}
EOF
