#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain="$2"

echo "\"${_keepassxc_cli_with_args}\" \"${options}\" show \"${keychain}\" {4} <<< \"${PW_KEYCHAIN_PASSWORD}\""
