#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_options="$(dirname "$0")/_keepassxc_cli_with_options"

options="$1" keychain_password="$2" keychain="$3"

echo "\"${_keepassxc_cli_with_options}\" \"${options}\" show \"${keychain}\" {4} <<< \"${keychain_password}\""
