#!/usr/bin/env bash
set -euo pipefail
"$(dirname "$0")/_require"

options="$1" keychain="$2"

declare -a cmd_options=()

parse_options() {
  local IFS=, key value
  for pair in ${options}; do
    key="${pair%%=*}"
    value="${pair#*=}"
    case "${key}" in
      keyfile) cmd_options+=("--set-key-file" "${value}") ;;
    esac
  done
}

parse_options

if [[ -p /dev/stdin ]]; then
  IFS= read -r password
  keepassxc-cli db-create --quiet "${cmd_options[@]}" --set-password "${keychain}" << EOF
${password}
${password}
EOF
else
  keepassxc-cli db-create "${cmd_options[@]}" --set-password "${keychain}"
fi
