#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain_password="$2" keychain="$3" format="${4:-default}"

if ! list="$("${_keepassxc_cli_with_args}" "${options}" ls --flatten --recursive "${keychain}" <<< "${keychain_password}" | { grep -v -e '/$' -e 'Recycle Bin/' || true; } | sort -f)"
then
  echo "Error while reading the database ${keychain}: Invalid credentials were provided, please try again." >&2
  exit 1
fi

if [[ "${list}" != "[empty]" ]]; then
  case "${format}" in
    fzf) awk '{print $0 "\t\t\t" $0}' <<< "${list}" ;;
    *) echo "${list}" ;;
  esac
fi
