#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

keychain="$1" format="${2:-default}"

if ! list="$("${_keepassxc_cli_with_args}" ls --flatten --recursive "${keychain}" <<< "${PW_KEYCHAIN_PASSWORD}" | { grep -v -e '/$' -e 'Recycle Bin/' || true; } | sort -f)"
then
  echo "Error while reading the database ${keychain}: Invalid credentials were provided, please try again." >&2
  exit 1
fi

if [[ "${list}" != "[empty]" ]]; then
  case "${format}" in
    fzf) echo "${list}" | awk '{print $0 "\t\t\t" $0}' ;;
    *) echo "${list}" ;;
  esac
fi
