#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain_password="$2" keychain="$3" name="$4" account="$5" url="$6"

"${_keepassxc_cli_with_args}" "${options}" rm "${keychain}" "${name}" <<< "${keychain_password}"
