#!/usr/bin/env bash
set -euo pipefail
_keepassxc_cli_with_args="$(dirname "$0")/_keepassxc_cli_with_args"

options="$1" keychain="$2" name="$3" account="$4" url="$5"

"${_keepassxc_cli_with_args}" "${options}" show "${keychain}" "${name}" <<< "${PW_KEYCHAIN_PASSWORD}"
