#!/usr/bin/env bash
set -e
[[ ! -f test/bats/bin/bats ]] && git submodule update --init --recursive

declare -rx TEST_BASH_VERSION="${TEST_BASH_VERSION:-"5.2"}"

run_tests() {
  DOCKER_BUILDKIT=1 docker build --target test -t "sschmid/pw/test/$1" -f "docker/$1/Dockerfile" .
}

while getopts ":aj:p:" options; do
  case "${options}" in
    a)
      run_tests alpine
      run_tests archlinux
      run_tests debian
      run_tests fedora
      run_tests ubuntu
      ;;
    j)
      jobs="${OPTARG}"
      ;;
    p)
      run_tests "${OPTARG}"
      exit
      ;;
    *)
      echo "Invalid option: -${OPTARG}" >&2
      exit 1
      ;;
  esac
done
shift $(( OPTIND - 1 ))

test/bats/bin/bats --jobs "${jobs:-1}" "${@:-test}"
test/shellcheck
