#!/usr/bin/env bash
set -e
[[ ! -f test/bats/bin/bats ]] && git submodule update --init --recursive

declare -rx TEST_BASH_VERSION="${TEST_BASH_VERSION:-"5.2"}"

run_tests() {
  DOCKER_BUILDKIT=1 docker build --target test -t "sschmid/pw/test/$1" -f "docker/$1/Dockerfile" .
}

cmd_options=()
no_shellcheck=0
while getopts ":ac:j:mp:" options; do
  case "${options}" in
    a)
      run_tests alpine
      run_tests archlinux
      run_tests debian
      run_tests fedora
      run_tests opensuse-tumbleweed
      run_tests ubuntu
      ;;
    c)
      case "${OPTARG}" in
        no-shellcheck) no_shellcheck=1 ;;
      esac
      ;;
    j)
      cmd_options+=("--jobs" "${OPTARG}")
      ;;
    m)
      export PW_TEST_RUN_MANUAL_TESTS=1
      cmd_options+=("--tap")
      ;;
    p)
      run_tests "${OPTARG}"
      exit
      ;;
    *)
      echo "Invalid option: -${OPTARG}" >&2
      exit 1
      ;;
  esac
done
shift $(( OPTIND - 1 ))

test/bats/bin/bats "${cmd_options[@]}" "${@:-test}"
(( no_shellcheck )) || test/shellcheck
