#!/usr/bin/env bash
# shellcheck disable=SC2046
docker pull koalaman/shellcheck
docker run --rm -v "${PWD}:/mnt" koalaman/shellcheck $(
  echo "src/pw" &&
  find "src" -type f -name "*.bash" &&
  find "test" -type f -maxdepth 1 -name "*.bash" -or -name "*.bats"
)
