#!/usr/bin/env bash
# shellcheck disable=SC2046
shellcheck $(
  echo "src/pw" &&
  find "src" "test/fixtures" -type f -name "*.bash" &&
  find "test" -type f -maxdepth 1 -name "*.bash" -or -name "*.bats"
)
