#!/usr/bin/env bash
#
# To install, run
# curl -fsSL https://raw.githubusercontent.com/sschmid/pw/main/install | bash
#
# To uninstall, run
# ~/.local/share/pw/install --uninstall

set -e

REPO="https://github.com/sschmid/pw-terminal-password-manager"
INST_DIR="${XDG_DATA_HOME:-"${HOME}/.local/share"}/pw"
BIN_DIR="${XDG_BIN_HOME:-"${HOME}/.local/bin"}"
BIN_PATH="${BIN_DIR}/pw"

if [[ $1 == "--uninstall" ]]; then
	rm -rf "${INST_DIR}" "${BIN_PATH}"
	echo "pw has been uninstalled successfully"
	exit
fi

if [[ ! -d "${INST_DIR}" ]]; then
	mkdir -p "${INST_DIR%/*}" "${BIN_DIR}"
	git clone "${REPO}" "${INST_DIR}"
	ln -sf "${INST_DIR}/src/pw" "${BIN_PATH}"
	echo "pw has been installed successfully to ${BIN_PATH}"
else
	git -C "${INST_DIR}" switch main
	git -C "${INST_DIR}" pull
	echo "pw has been updated successfully"
fi

if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
	cat <<EOF

${BIN_DIR} is not currently in your PATH.

Add the following line to your shell configuration:

  export PATH="\$HOME/.local/bin:\$PATH"

EOF
fi
