#!/usr/bin/env bash
set -euo pipefail

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7" notes="$8"

echo "test add <${options}> <${keychain_password}> <${keychain}> <${password}> <${name}> <${account}> <${url}> <${notes}>"
