#!/usr/bin/env bash
set -euo pipefail

IFS= read -r keychain_password
IFS= read -r password

options="$1" keychain="$2" name="$3" account="$4" url="$5"

echo "test edit <${options}> <${keychain_password}> <${keychain}> <${password}> <${name}> <${account}> <${url}>"
