#!/usr/bin/env bash
set -euo pipefail

IFS= read -r keychain_password

options="$1" keychain="$2" name="$3" account="$4" url="$5"

if [[ -v PW_TEST_PLUGIN_SHORT ]]; then
	echo "${name}"
else
	echo "test get <${options}> <${keychain_password}> <${keychain}> <${name}> <${account}> <${url}>"
fi
