#!/usr/bin/env bash
set -euo pipefail

IFS= read -r keychain_password

options="$1" keychain="$2" format="${3:-default}"

[[ -v PW_TEST_PLUGIN_FAIL ]] && exit 1

if [[ -v PW_TEST_PLUGIN_LS ]]; then
	case "${PW_TEST_PLUGIN_LS}" in
		1)
			echo -e "name 1\taccount 1\turl 1\tname 1\taccount 1\turl 1"
			echo -e "name 2\taccount 2\turl 2\tname 2\taccount 2\turl 2"
			echo -e "name 3\taccount 3\turl 3\tname 3\taccount 3\turl 3"
			;;
		2)
			echo -e "name 1\t\t\tname 1"
			echo -e "name 2\t\t\tname 2"
			echo -e "name 3\t\t\tname 3"
			;;
esac

else
	echo "test ls <${options}> <${keychain_password}> <${keychain}> <${format}>"
fi
