#!/usr/bin/env bash
set -euo pipefail

IFS= read -r keychain_password

options="$1" keychain="$2" rename="$3" name="$4" account="$5" url="$6"

echo "test mv <${options}> <${keychain_password}> <${keychain}> <${rename}> <${name}> <${account}> <${url}>"
