#!/usr/bin/env bash
set -euo pipefail
"$(dirname "$0")/_require"

if [[ -v PW_KEYCHAIN_PASSWORD ]]
then gpg --quiet --batch --pinentry-mode loopback --passphrase "${PW_KEYCHAIN_PASSWORD}" "$@"
else gpg --quiet "$@"
fi
