#!/usr/bin/env bash
set -euo pipefail
_gpg="$(dirname "$0")/_gpg"

options="$1"; shift

declare -a cmd_options=()

parse_options() {
  local IFS=, key value
  for pair in ${options}; do
    key="${pair%%=*}"
    value="${pair#*=}"
    case "${key}" in
      key) cmd_options+=("--default-key" "${value}") ;;
    esac
  done
}

parse_options

"${_gpg}" --encrypt "${cmd_options[@]}" --default-recipient-self "$@"
