#!/usr/bin/env bash
set -euo pipefail
"$(dirname "$0")/_require"

keychain_password="$1"; shift

if [[ -n "${keychain_password}" ]]
then gpg --quiet --batch --pinentry-mode loopback --passphrase "${keychain_password}" "$@"
else gpg --quiet "$@"
fi
