#!/usr/bin/env bash
set -euo pipefail
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"

keychain="$1" password="$2" name="$3" account="$4" url="$5" notes="$6"

# shellcheck disable=SC2174
mkdir -m 700 -p "${keychain}"

mkdir -p "${keychain}/$(dirname "${name}")"

content="${password}
${account}
${url}
${notes}"

if [[ "${name##*.}" == "asc" ]]
then "${_gpg_encrypt}" --output "${keychain}/${name}" --armor <<< "${content}"
else "${_gpg_encrypt}" --output "${keychain}/${name}" <<< "${content}"
fi
