#!/usr/bin/env bash
set -euo pipefail
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7" notes="$8"

# shellcheck disable=SC2174
mkdir -m 700 -p "${keychain}"

mkdir -p "${keychain}/$(dirname "${name}")"

content="${password}
${account}
${url}
${notes}"

if [[ "${name##*.}" == "asc" ]]
then "${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" --armor <<< "${content}"
else "${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" <<< "${content}"
fi
