#!/usr/bin/env bash
set -euo pipefail
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"

options="$1" keychain="$2" password="$3" name="$4" account="$5" url="$6" notes="$7"

# shellcheck disable=SC2174
mkdir -m 700 -p "${keychain}"

mkdir -p "${keychain}/$(dirname "${name}")"

content="${password}
${account}
${url}
${notes}"

if [[ "${name##*.}" == "asc" ]]
then "${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" --armor <<< "${content}"
else "${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" <<< "${content}"
fi
