#!/usr/bin/env bash
set -euo pipefail
_gpg="$(dirname "$0")/_gpg"
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"

options="$1" keychain="$2" password="$3" name="$4" account="$5" url="$6"

content="$("${_gpg}" --decrypt "${keychain}/${name}" | sed -n 2,\$p)"
"${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" --yes << EOF
${password}
${content}
EOF
