#!/usr/bin/env bash
set -euo pipefail
_gpg="$(dirname "$0")/_gpg"
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"
_parse_details="$(dirname "$0")/_parse_details"

options="$1" keychain_password="$2" keychain="$3"

# KCOV_EXCL_START
# shellcheck disable=SC1083
_fzf_preview() {
  gpg --quiet --decrypt "${keychain}/"{4} | "${_parse_details}" {4}
}
# KCOV_EXCL_STOP

# unlocks the keychain if necessary and only previews if the keychain is unlocked
if echo | "${_gpg_encrypt}" "${options}" | "${_gpg}" "${keychain_password}" --decrypt &>/dev/null; then
  declare -p keychain _parse_details
  declare -f _fzf_preview
  echo "_fzf_preview"
fi
