#!/usr/bin/env bash
set -euo pipefail
_gpg="$(dirname "$0")/_gpg"

options="$1" keychain_password="$2" keychain="$3" name="$4" account="$5" url="$6"

"${_gpg}" --decrypt "${keychain}/${name}" | sed -n 1p
