#!/usr/bin/env bash
set -euo pipefail

FILE_TYPE="PGP"
FILE_EXTENSION="/, gpg, asc"

case "$1" in
  discover_keychains)
    while read -r path; do
      filetype="$(file -b "${path}")"
      # .asc
      [[ "${filetype}" != "${FILE_TYPE}"* ]] || echo "$(dirname "${path}")/"
      # .gpg
      [[ "${filetype}" != "data" ]] || echo "$(dirname "${path}")/"
    done < <(find "${PWD}" -maxdepth 1 -type f)
  ;;
  register_with_keychain)
    echo "${FILE_TYPE}"
    if [[ -d "$2" ]]; then
      echo yes
    else
      echo no
    fi
  ;;
  register_with_extension)
    echo "${FILE_TYPE}"
    echo "${FILE_EXTENSION}"
    if [[ "$2" == */ ]]; then
      echo yes
    else
      echo no
    fi
  ;;
esac
