#!/usr/bin/env bash
set -euo pipefail
_gpg="$(dirname "$0")/_gpg"
_gpg_encrypt="$(dirname "$0")/_gpg_encrypt"

options="$1" keychain="$2"

if [[ -p /dev/stdin ]]; then
  IFS= read -r keychain_password
else
  keychain_password=""
fi

echo | "${_gpg_encrypt}" "${options}" | "${_gpg}" "${keychain_password}" --decrypt >/dev/null
