#!/usr/bin/env bash
set +x -euo pipefail
"$(dirname -- "${BASH_SOURCE[0]}")/_require"

IFS= read -r keychain_password

path="${1:-}"

if [[ -n "${keychain_password}" ]]; then
	gpg --quiet --batch \
			--pinentry-mode loopback --passphrase-fd 0 \
			--decrypt ${path:+"${path}"} <<< "${keychain_password}"
else
	gpg --quiet --decrypt ${path:+"${path}"}
fi
