#!/usr/bin/env bash
set -euo pipefail
"$(dirname "$0")/_require"

keychain_password="$1" path="${2:-}"

if [[ -n "${keychain_password}" ]]; then
	gpg --quiet --batch \
			--pinentry-mode loopback --passphrase "${keychain_password}" \
			--decrypt ${path:+"${path}"}
else
	gpg --quiet --decrypt ${path:+"${path}"}
fi
