#!/usr/bin/env bash
set +x -euo pipefail

awk -v name="$(basename -- "$1")" '
NR==2 { account=$0 }
NR==3 { url=$0 }
NR>=4 { notes = (notes ? notes "\n" : "") $0 }
END { printf "Name: %s\nAccount: %s\nURL: %s\nNotes:\n%s", name, account, url, notes }'
