#!/usr/bin/env bash
set -euo pipefail
_gpg_encrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_encrypt"

IFS= read -r _
IFS= read -r password

# options="$1" keychain="$2" name="$3" account="$4" url="$5" notes="$6"
options="$1" keychain="$2" name="$3" account="$4" url="$5" notes="$6"

# shellcheck disable=SC2174
mkdir -m 700 -p "${keychain}"

mkdir -p "${keychain}/$(dirname "${name}")"

content="${password}
${account}
${url}
${notes}"

if [[ "${name##*.}" == "asc" ]]
then "${_gpg_encrypt}" "${options}" --armor --output "${keychain}/${name}" <<< "${content}"
else "${_gpg_encrypt}" "${options}" --output "${keychain}/${name}" <<< "${content}"
fi
