#!/usr/bin/env bash
set -euo pipefail
_gpg_decrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_decrypt"
_gpg_encrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_encrypt"

IFS= read -r keychain_password
IFS= read -r password

# options="$1" keychain="$2" name="$3" account="$4" url="$5"
options="$1" keychain="$2" name="$3"

content="$("${_gpg_decrypt}" "${keychain}/${name}" <<< "${keychain_password}" | sed '1d')"
"${_gpg_encrypt}" "${options}" --yes --output "${keychain}/${name}" <<EOF
${password}
${content}
EOF
