#!/usr/bin/env bash
set -euo pipefail

FILE_TYPE="PGP"
FILE_EXTENSION="/, gpg, asc"

discover() {
	local -a paths args=() find_cmd=(find "${PWD}" -maxdepth 1)
	local path

	IFS=';' read -r -a paths <<< "${PW_GPG_IGNORE_PATHS:-}"
	for path in "${paths[@]}"; do
		args+=(-path "${path}" -o)
	done

	if (( ${#args[@]} )); then
		unset 'args[${#args[@]}-1]'
		find_cmd+=(\( "${args[@]}" \) -prune -o)
	fi
	find_cmd+=(-type f -print0)

	"${find_cmd[@]}"
}

case "$1" in
	discover_keychains)
		while IFS= read -r -d '' path; do
			filetype="$(file -b -- "${path}")"
			# .asc
			[[ "${filetype}" != "${FILE_TYPE}"* ]] || echo "$(dirname "${path}")/"
			# .gpg
			[[ "${filetype}" != "data" ]] || echo "$(dirname "${path}")/"
		done < <(discover)
	;;
	register_with_keychain)
		echo "${FILE_TYPE}"
		if [[ -d "$2" ]]; then
			echo yes
		else
			echo no
		fi
	;;
	register_with_extension)
		echo "${FILE_TYPE}"
		echo "${FILE_EXTENSION}"
		if [[ "$2" == */ ]]; then
			echo yes
		else
			echo no
		fi
	;;
esac
