#!/usr/bin/env bash
set -euo pipefail

options="$1" command="$2" keychain="$3"

if [[ "${command}" == "get" || "${command}" == "show" || "${command}" == "edit" ]]; then
	if [[ -p /dev/stdin ]]; then
		IFS= read -r keychain_password
		echo "${keychain_password}"
	fi
fi
