#!/usr/bin/env bash
set +x -euo pipefail

# options="$1" command="$2" keychain="$3"
command="$2"

if [[ "${command}" == "get" || "${command}" == "show" || "${command}" == "edit" ]]; then
	if [[ -p /dev/stdin ]]; then
		IFS= read -r keychain_password
		printf '%s' "${keychain_password}"
	fi
fi
