#!/usr/bin/env bash
set +x -euo pipefail

IFS= read -r _

# options="$1" keychain="$2" rename="$3" name="$4" account="$5" url="$6"
keychain="$2" rename="$3" name="$4"

mkdir -p "${keychain}/$(dirname -- "${rename}")"
mv "${keychain}/${name}" "${keychain}/${rename}"
