#!/usr/bin/env bash
set -euo pipefail
_gpg_decrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_decrypt"
_parse_details="$(dirname -- "${BASH_SOURCE[0]}")/_parse_details"

IFS= read -r keychain_password

# options="$1" keychain="$2" name="$3" account="$4" url="$5"
keychain="$2" name="$3"

"${_gpg_decrypt}" "${keychain}/${name}" <<< "${keychain_password}" | "${_parse_details}" "${name}"
