#!/usr/bin/env bash
set -euo pipefail
_gpg_decrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_decrypt"
_gpg_encrypt="$(dirname -- "${BASH_SOURCE[0]}")/_gpg_encrypt"

# options="$1" keychain="$2"
options="$1"

if [[ -p /dev/stdin ]]
then IFS= read -r keychain_password
else keychain_password=""
fi

"${_gpg_decrypt}" <("${_gpg_encrypt}" "${options}" <<< "") <<< "${keychain_password}" >/dev/null
