#!/usr/bin/env bash
set -euo pipefail

keychain="$1" password="$2" name="$3" account="$4" url="$5" notes="$6"

security add-generic-password \
  -l "${name:-"${url}"}" \
  -a "${account}" \
  -s "${url:="${name}"}" \
  ${notes:+-j "${notes}"} \
  -w "${password}" \
  "${keychain}"
