#!/usr/bin/env bash
set -euo pipefail

options="$1" keychain="$2" password="$3" name="$4" account="$5" url="$6"

security add-generic-password -U \
  -l "${name:-"${url}"}" \
  -a "${account}" \
  -s "${url:="${name}"}" \
  -w "${password}" \
  "${keychain}"
