#!/usr/bin/env bash
set -euo pipefail
_parse_details="$(dirname "$0")/_parse_details"

options="$1" keychain_password="$2" keychain="$3"

# KCOV_EXCL_START
# shellcheck disable=SC1083
_fzf_preview() {
  security find-generic-password -l {4} -a {5} -s {6} -g "${keychain}" 2>/dev/null \
  | "${_parse_details}" 'printf "Name: %s\nAccount: %s\nWhere: %s\nComments:\n%s\n", label, account, service, comments'
}
# KCOV_EXCL_STOP

declare -p keychain _parse_details
declare -f _fzf_preview
echo "_fzf_preview"
