#!/usr/bin/env bash
set -euo pipefail

options="$1" keychain="$2" name="$3" account="$4" url="$5"

security find-generic-password \
  ${name:+-l "${name}"} \
  ${account:+-a "${account}"} \
  ${url:+-s "${url}"} \
  -w "${keychain}"
