#!/usr/bin/env bash
set -euo pipefail
_get_details="$(dirname "$0")/_get_details"

keychain="$1" format="${2:-default}"

case "${format}" in
  fzf) printf_format='printf "%-24s\t%-24s\t%s\t%s\t%s\t%s\n", label, account, service, label, account, service' ;;
  *) printf_format='printf "%-24s\t%-24s\t%s\n", label, account, service' ;;
esac

security dump-keychain "${keychain}" | "${_get_details}" "${printf_format}" | sort -f
