#!/usr/bin/env bash
set -euo pipefail

options="$1" keychain_password="$2" keychain="$3" name="$4" account="$5" url="$6"

security delete-generic-password \
  ${name:+-l "${name}"} \
  ${account:+-a "${account}"} \
  ${url:+-s "${url}"} \
  "${keychain}" >/dev/null
