#!/usr/bin/env bash
set -euo pipefail
_get_details="$(dirname "$0")/_get_details"

options="$1" keychain_password="$2" keychain="$3" name="$4" account="$5" url="$6"

security find-generic-password \
  ${name:+-l "${name}"} \
  ${account:+-a "${account}"} \
  ${url:+-s "${url}"} \
  -g "${keychain}" 2> /dev/null \
| "${_get_details}" 'printf "Name: %s\nAccount: %s\nWhere: %s\nComments:\n%s\n", label, account, service, comments'
