#!/usr/bin/env bash
set -euo pipefail

keychain="$1"

if [[ -p /dev/stdin ]]; then
  IFS= read -r password
  security unlock-keychain -p "${password}" "${keychain}"
else
  security unlock-keychain "${keychain}"
fi
