#!/usr/bin/env bash
# added Oct 2024
set -euo pipefail
IFS=$'\n\t'

pw_rc="$1"

if grep "PW_KEYCHAINS" "${pw_rc}" >/dev/null ; then
  IFS= read -rp "pw 9.0.0 introduced a new .pwrc format. Would you like to automatically upgrade your .pwrc file? (y / N): " answer >&2
  [[ "${answer}" == [yY] ]] || exit 1

  # shellcheck disable=SC1090
  source "${pw_rc}"
  echo "${PW_KEYCHAINS[*]}" > "${pw_rc}"
fi
