#!/usr/bin/env bash
set -euo pipefail

options="$1" keychain_password="$2" keychain="$3" password="$4" name="$5" account="$6" url="$7" notes="$8"

echo "plugin modify add ${name} ${account} ${url} ${password} ${keychain}"
