#!/usr/bin/env bash
set -euo pipefail

FILE_TYPE="Test File Type Modify"
FILE_EXTENSION="extm"

export PW_TEST_PLUGIN_FAIL=1
PW_KEYCHAIN+=" #modified-soure"

case "$1" in
  discover_keychains) PW_KEYCHAIN+=" #modified}";;
  register_with_keychain)
    echo "${FILE_TYPE}"
    PW_KEYCHAIN+=" #modified}"
    echo no
  ;;
  register_with_extension)
    echo "${FILE_TYPE}"
    echo "${FILE_EXTENSION}"
    PW_KEYCHAIN+=" #modified}"
    echo no
  ;;
esac
