FROM alpine:latest AS base
WORKDIR /root/.local/share/pw
COPY DEPENDENCIES .
RUN apk add --no-cache \
    $(cat DEPENDENCIES) \
    parallel \
    xclip \
    xvfb

FROM base AS pw
WORKDIR /root/.local/share/pw
COPY src src
COPY examples examples
COPY lib lib
COPY plugins plugins
COPY version.txt .
RUN ln -s /opt/pw/src/pw /usr/local/bin/pw
WORKDIR /workspaces
COPY container/entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]

FROM pw AS test
WORKDIR /root/.local/share/pw
COPY test test
RUN test/bats/bin/bats test
