#!/usr/bin/env bash
set +x -euo pipefail

IFS= read -r _
IFS= read -r password

# options="$1" keychain="$2" name="$3" account="$4" url="$5" notes="$6"
keychain="$2" name="$3" account="$4" url="$5" notes="$6"

[[ "${PW_MACOS_KEYCHAIN_ACCESS_CONTROL:-}" == "always-allow" ]] || access_control="confirm"

security add-generic-password \
	-l "${name:-"${url}"}" \
	-a "${account}" \
	-s "${url:-"${name}"}" \
	${notes:+-j "${notes}"} \
	${access_control:+-T ""} \
	-w "${password}" \
	"${keychain}"
