#!/usr/bin/env bash
set +x -euo pipefail

IFS= read -r _
IFS= read -r password

# options="$1" keychain="$2" name="$3" account="$4" url="$5"
keychain="$2" name="$3" account="$4" url="$5"

security add-generic-password -U \
	-l "${name:-"${url}"}" \
	-a "${account}" \
	-s "${url:-"${name}"}" \
	-w "${password}" \
	"${keychain}"
