#!/usr/bin/env bash
set +x -euo pipefail
_parse_details="$(dirname -- "${BASH_SOURCE[0]}")/_parse_details"

IFS= read -r _

# options="$1" keychain="$2"
keychain="$2"

# KCOV_EXCL_START
# shellcheck disable=SC1083
_fzf_preview() {
	security find-generic-password -l {4} -a {5} -s {6} "${keychain}" |
		"${_parse_details}" 'printf "Name: %s\nAccount: %s\nWhere: %s\nComments:\n%s\n", label, account, service, comments'
}
# KCOV_EXCL_STOP

declare -p keychain _parse_details
declare -f _fzf_preview
echo "_fzf_preview"
