#!/usr/bin/env bash
set +x -euo pipefail
_parse_details="$(dirname -- "${BASH_SOURCE[0]}")/_parse_details"

IFS= read -r _

# options="$1" keychain="$2" format="${3:-default}"
keychain="$2" format="${3:-default}"

case "${format}" in
	fzf) printf_format='printf "%-24s\t%-16s\t%s\t%s\t%s\t%s\n", label, account, service, label, account, service' ;;
	*) printf_format='printf "%-24s\t%-16s\t%s\n", label, account, service' ;;
esac

security dump-keychain "${keychain}" | "${_parse_details}" "${printf_format}" | sort -f
