#!/usr/bin/env bash
set +x -euo pipefail
_parse_details="$(dirname -- "${BASH_SOURCE[0]}")/_parse_details"

IFS= read -r _

# options="$1" keychain="$2" name="$3" account="$4" url="$5"
keychain="$2" name="$3" account="$4" url="$5"

security find-generic-password \
	${name:+-l "${name}"} \
	${account:+-a "${account}"} \
	${url:+-s "${url}"} \
	"${keychain}" \
| "${_parse_details}" 'printf "Name: %s\nAccount: %s\nWhere: %s\nComments:\n%s\n", label, account, service, comments'
