#!/usr/bin/env bash
set +x -euo pipefail
IFS=$'\n\t'

if (( ! $# )); then
	printf 'error: config file not specified\n' >&2
	exit 1
fi

config_file="$1"
if [[ ! -f "${config_file}" ]]; then
	printf 'error: config file not found: %s\n' "${config_file}" >&2
	exit 1
fi

section="$2"

awk -v wanted="${section}" '{
	line = $0

	sub(/^[[:space:]]+/, "", line)
	sub(/[[:space:]]+$/, "", line)

	if (line == "" || line ~ /^[#;]/)
		next

	if (line ~ /^\[.*\]$/) {
		section = line
		sub(/^\[/, "", section)
		sub(/\]$/, "", section)
		next
	}

	if (wanted != "" && section != wanted)
		next

	while (line ~ /\\$/) {
		line = substr(line, 1, length(line) - 1)

		while (1) {
			if (getline next_line <= 0)
				break

			sub(/^[[:space:]]+/, "", next_line)
			sub(/[[:space:]]+$/, "", next_line)

			if (next_line == "" || next_line ~ /^[#;]/)
				continue
			break
		}

		line = line next_line
	}

	eq = index(line, "=")

	if (!eq)
		next

	key = substr(line, 1, eq - 1)
	value = substr(line, eq + 1)

	sub(/^[[:space:]]+/, "", key)
	sub(/[[:space:]]+$/, "", key)
	sub(/^[[:space:]]+/, "", value)
	sub(/[[:space:]]+$/, "", value)

	if (value != "")
		printf "%s\t%s\t%s\n", section, key, value
}' "${config_file}"
