#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ -v PW_COPY ]]; then
	eval "${PW_COPY}"
	exit
fi

if   command -v pbcopy  &>/dev/null; then pbcopy
elif command -v xclip   &>/dev/null; then xclip -selection clipboard
elif command -v xsel    &>/dev/null; then xsel --clipboard --input
elif command -v wl-copy &>/dev/null; then wl-copy
else
	echo "No clipboard tool found!" >&2
	echo "Supported tools: pbcopy, xclip, xsel, wl-copy" >&2
	exit 1
fi
