#!/usr/bin/env bash
set +x -euo pipefail
IFS=$'\n\t'

if [[ -t 0 ]]; then
	while :; do
		IFS= read -rsp "Enter password for '${PW_NAME}' (leave empty to generate password):"$'\n' password
		if [[ -n "${password}" ]]; then
			IFS= read -rsp "Retype password for '${PW_NAME}':"$'\n' retype
			if [[ "${retype}" == "${password}" ]]; then
				printf '%s' "${password}"
				break
			else
				echo "Passwords do not match. Please try again."
			fi
		else
			password-generate
		fi
	done
else
	cat
fi
