#!/usr/bin/env bash
set +x -eu
IFS=$'\n\t'

declare -i length=${1:-${PW_GEN_LENGTH}}
class="${2:-"${PW_GEN_CLASS}"}"

# Fix character classes for BusyBox tr
[[ "${class}" == "[:graph:]" ]] && class="[:alnum:][:punct:]"
[[ "${class}" == "[:print:]" ]] && class="[:alnum:][:punct:][:space:]"

LC_CTYPE=C LC_ALL=C tr -dc "${class}" < /dev/urandom 2>/dev/null | head -c "${length}"
