#!/usr/bin/env bash
set +x -euo pipefail
IFS=$'\n\t'

declare -i length=${1:-${PW_GEN_LENGTH}}
class="${2:-"${PW_GEN_CLASS}"}"

declare -i block_size=$(( length / 32 ))
(( block_size )) || block_size=1

# Fix character classes for BusyBox tr
[[ "${class}" == "[:graph:]" ]] && class="[:alnum:][:punct:]"
[[ "${class}" == "[:print:]" ]] && class="[:alnum:][:punct:][:space:]"

while :; do
	dd if=/dev/urandom bs=${block_size} count=1 status=none 2>/dev/null |
		LC_CTYPE=C LC_ALL=C tr -dc "${class}"
done | head -c ${length}
