#!/usr/bin/env bash
set +x -euo pipefail
IFS=$'\n\t'

name="$1"

if [[ -t 0 ]]; then
	while :; do
		IFS= read -rsp "Enter password for '${name}' (leave empty to generate password):"$'\n' password >&2
		if [[ -n "${password}" ]]; then
			IFS= read -rsp "Retype password for '${name}':"$'\n' retype
			if [[ "${retype}" == "${password}" ]]; then
				printf '%s' "${password}"
				break
			else
				echo "Passwords do not match. Please try again." >&2
			fi
		else
			password-generate
			break
		fi
	done
else
	cat
fi
