#!/usr/bin/env bash
set -euo pipefail

FILE_TYPE="Test File Type 2"
FILE_EXTENSION="ext2"

case "$1" in
  discover_keychains)
    if [[ -v PW_TEST_PLUGIN_2 ]]; then
      echo "test 2 keychain"
      echo "test 2 keychain"
      echo "test 2 keychain"
    fi
  ;;
  register_with_keychain)
    echo "${FILE_TYPE}"
    if [[ -v PW_TEST_PLUGIN_2 ]]; then
      echo yes
    else
      echo no
    fi
  ;;
  register_with_extension)
    echo "${FILE_TYPE}"
    echo "${FILE_EXTENSION}"
    if [[ -v PW_TEST_PLUGIN_2 ]]; then
      echo yes
    else
      echo no
    fi
  ;;
esac
