name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: brew install bash fzf gnupg shellcheck
      - run: brew install --cask keepassxc
      - run: test/run
