FROM archlinux:latest AS base
# FROM --platform=linux/amd64 archlinux:latest AS base
WORKDIR /root/.local/share/pw
COPY DEPENDENCIES .
RUN pacman -Syu --noconfirm && pacman -S --noconfirm --needed \
    $(cat DEPENDENCIES) \
    parallel \
    xclip \
    xorg-server-xvfb \
    && pacman -Scc --noconfirm

FROM base AS pw
WORKDIR /root/.local/share/pw
COPY src src
COPY examples examples
COPY lib lib
COPY plugins plugins
COPY version.txt .
RUN ln -s /opt/pw/src/pw /usr/local/bin/pw
WORKDIR /workspaces
COPY container/entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]

FROM pw AS test
WORKDIR /root/.local/share/pw
COPY test test
RUN test/bats/bin/bats test
